name: Semgrep Full Scan

on:
  workflow_dispatch:

jobs:
  semgrep-full:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Run Semgrep full scan
        run: |
          semgrep \
            --config="p/default" \
            --output report.sarif \
            --sarif

      - name: Upload scan report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: semgrep-report
          path: report.sarif
